# Generated by Django 2.2.4 on 2021-02-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0002_auto_20210223_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(default=4.30264828001635e-05),
        ),
    ]
