# Generated by Django 2.2.4 on 2021-02-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0004_auto_20210223_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(),
        ),
    ]
