# Generated by Django 2.2.4 on 2021-02-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0005_auto_20210223_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='releasedate_new',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
