# Generated by Django 2.2.4 on 2021-02-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0007_auto_20210223_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='release_date',
            new_name='releasedate_new',
        ),
    ]
