# Generated by Django 2.2.4 on 2021-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0009_auto_20210223_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='release_date_old',
            field=models.DateTimeField(null=True),
        ),
    ]
