# Generated by Django 2.2.4 on 2021-02-24 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0010_shows_release_date_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='release_date_old',
        ),
        migrations.AddField(
            model_name='shows',
            name='release_datenew',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateTimeField(),
        ),
    ]
