# Generated by Django 2.2.4 on 2021-02-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0011_auto_20210224_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='release_datenew',
        ),
    ]
